## This code demonstrates the one_hot_encoding using 2 different methods in 1D
## 1. using torch.stack()
## 2. using torch.tensor.scatter_() 
       + this would require torch.unsqueeze()



## Step 1: Define the input_data: x

In [2]:
import torch 

## Method 1  using torch.stack()

In [26]:
# Case 1 : no mising labels or repeating labels 
# defining the input data
x = torch.tensor([0, 1, 2, 3])
print('input data size =', x.size())
print('_______________________________\n')

print('input data : ',x)
print('_______________________________\n')


values = [x==i for i in range(int(x.max())+1)] # unique list 
z = torch.stack(values, dim=0).float()
print('masks size : ',z.size())
print('_______________________________\n')
print('mask : \n ',z)

input data size = torch.Size([4])
_______________________________

input data :  tensor([0, 1, 2, 3])
_______________________________

masks size :  torch.Size([4, 4])
_______________________________

mask : 
  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [27]:
# Case 2 : mising labels
# defining the input data
x = torch.tensor([0, 1, 2, 4])
print('input data size =', x.size())
print('_______________________________\n')

print('input data : ',x)
print('_______________________________\n')


values = [x==i for i in range(int(x.max())+1)] # unique list 
z = torch.stack(values, dim=0).float()
print('masks size : ',z.size())
print('_______________________________\n')
print('mask : \n ',z)




input data size = torch.Size([4])
_______________________________

input data :  tensor([0, 1, 2, 4])
_______________________________

masks size :  torch.Size([5, 4])
_______________________________

mask : 
  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]])


In [59]:
# Case 3 : repeating labels
# defining the input data
x = torch.tensor([0, 1, 2, 3, 4, 1, 2])
print('input data size =', x.size())
print('_______________________________\n')

print('input data : ',x)
print('_______________________________\n')


values = [x==i for i in range(int(x.max())+1)] # unique list 
z = torch.stack(values, dim=0).float()
print('masks size : ',z.size())
print('_______________________________\n')
print('mask : \n ',z)



input data size = torch.Size([6])
_______________________________

input data :  tensor([0, 1, 2, 4, 1, 2])
_______________________________

masks size :  torch.Size([5, 6])
_______________________________

mask : 
  tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.]])


## Method 2 using torch.tensor_scatter_()

### Method 2 requires to understand torch.unsqueeze()
## Understanding torch.unsqueeze()


In [6]:
# torch.unsqueeze() for 1D tensor
x = torch.tensor([1, 2, 3, 4])
x_dim0 = torch.unsqueeze(x, 0)
x_dim1 = torch.unsqueeze(x, 1)
print('x size =',x.size())
print('x : \n',x)
print('_______________________________\n')

print('x_dim0 size =',x_dim0.size())
print('unsqueeze along dim 0 : \n',x_dim0)
print('_______________________________\n')
print('x_dim1 size =',x_dim1.size())
print('unsqueeze along dim 1 :\n',x_dim1)
print('_______________________________\n')





x size = torch.Size([4])
x : 
 tensor([1, 2, 3, 4])
_______________________________

x_dim0 size = torch.Size([1, 4])
unsqueeze along dim 0 : 
 tensor([[1, 2, 3, 4]])
_______________________________

x_dim1 size = torch.Size([4, 1])
unsqueeze along dim 1 :
 tensor([[1],
        [2],
        [3],
        [4]])
_______________________________



In [7]:
# torch.unsqueeze() for 2D tensor

y = torch.ones(4,4) # define a torch tensor
y[0,:]  = torch.tensor([0, 0, 2, 2]) 
y[1,:]  = torch.tensor([0, 0, 2, 2])
y[2,:]  = torch.tensor([3, 3, 1, 1]) 
y[3,:]  = torch.tensor([3, 3, 1, 1]) 
y_dim0 = torch.unsqueeze(y, 0)
y_dim1 = torch.unsqueeze(y, 1)

print('y size =',y.size())
print('y : \n',y)
print('_______________________________\n')

print('y_dim0 size =',y_dim0.size())
print('unsqueeze along dim 0 : \n',y_dim0)
print('_______________________________\n')
print('y_dim1 size =',y_dim1.size())
print('unsqueeze along dim 1 :\n',y_dim1)
print('_______________________________\n')



y size = torch.Size([4, 4])
y : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

y_dim0 size = torch.Size([1, 4, 4])
unsqueeze along dim 0 : 
 tensor([[[0., 0., 2., 2.],
         [0., 0., 2., 2.],
         [3., 3., 1., 1.],
         [3., 3., 1., 1.]]])
_______________________________

y_dim1 size = torch.Size([4, 1, 4])
unsqueeze along dim 1 :
 tensor([[[0., 0., 2., 2.]],

        [[0., 0., 2., 2.]],

        [[3., 3., 1., 1.]],

        [[3., 3., 1., 1.]]])
_______________________________



## learning torch.tensor.scatter_()

In [34]:
# +torch.scatter()  Out-of-place version of torch.Tensor.scatter_()
# +Syntax of torch.Tensor.scatter_():
#.       Tensor.scatter_(dim, index, src)

    

In [74]:
# Case 1 : no mising labels or repeating labels 
# defining the input data
x = torch.tensor([0, 1, 2, 3])
print('input data size =', x.size())
print('_______________________________\n')
print('input data : ',x)
print('_______________________________\n')


num_classes = (x.max()+1).int() # highest cardinal number of the label
mask = torch.zeros(num_classes, len(x))
print('masks size : ',mask.size())
print('_______________________________\n')


mask.scatter_(0, x.unsqueeze(0), 1)   ##(dim, index, src)
print('mask : \n ',mask)

input data size = torch.Size([4])
_______________________________

input data :  tensor([0, 1, 2, 3])
_______________________________

masks size :  torch.Size([4, 4])
_______________________________

mask : 
  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [75]:
# Case 2 : mising labels
# defining the input data
x = torch.tensor([0, 1, 2, 4])
print('input data size =', x.size())
print('_______________________________\n')
print('input data : ',x)
print('_______________________________\n')


num_classes = (x.max()+1).int() # highest cardinal number of the label
mask = torch.zeros(num_classes, len(x))
print('masks size : ',mask.size())
print('_______________________________\n')


mask.scatter_(0, x.unsqueeze(0), 1)   ##(dim, index, src)
print('mask : \n ',mask)

input data size = torch.Size([4])
_______________________________

input data :  tensor([0, 1, 2, 4])
_______________________________

masks size :  torch.Size([5, 4])
_______________________________

mask : 
  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.]])


In [69]:
# Case 3 : repeating labels
# defining the input data
x = torch.tensor([0, 1, 2,3, 4,1,2])
print('input data size =', x.size())
print('_______________________________\n')
print('input data : ',x)
print('_______________________________\n')

num_classes = (x.max()+1).int() # highest cardinal number of the label
mask = torch.zeros(num_classes, len(x))
print('masks size : ',mask.size())
print('_______________________________\n')


mask.scatter_(0, x.unsqueeze(0), 1)   ##(dim, index, src)
print('mask : \n ',mask)

input data size = torch.Size([7])
_______________________________

input data :  tensor([0, 1, 2, 3, 4, 1, 2])
_______________________________

masks size :  torch.Size([5, 7])
_______________________________

mask : 
  tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])
