## Thise code demonstartes the one_hot_encoding functionality using 3 different methods
## 1. using torch.stack()
## 2. using torch.tensor.scatter_() 
       + this would require torch.unsqueeze()
## 3. using torch.nn.functional.one_hot()


## Step 1: Define the input_data: x

In [19]:
import torch 

## Method 1  using torch.stack()

In [40]:
# defining the input data
# Case 1 : no mising labels or repeating labels 

x = torch.ones(4,4) 
x[0,:]  = torch.tensor([0, 0, 2, 2]) 
x[1,:]  = torch.tensor([0, 0, 2, 2])
x[2,:]  = torch.tensor([3, 3, 1, 1]) 
x[3,:]  = torch.tensor([3, 3, 1, 1]) 

values = [x==i for i in range(int(x.max())+1)] # unique list 
z = torch.stack(values, dim=0).float()
print('input data : \n \n',x)
print('_______________________________\n')
print('mask : \n ',z)

input data : 
 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

mask : 
  tensor([[[1., 1., 0., 0.],
         [1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 1.],
         [0., 0., 1., 1.]],

        [[0., 0., 1., 1.],
         [0., 0., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 0., 0.],
         [1., 1., 0., 0.]]])


In [41]:
# Case 2 : mising labels


x = torch.ones(4,4) 
x[0,:]  = torch.tensor([0, 0, 2, 2]) 
x[1,:]  = torch.tensor([0, 0, 2, 2])
x[2,:]  = torch.tensor([4, 4, 1, 1]) 
x[3,:]  = torch.tensor([4, 4, 1, 1]) 

values = [x==i for i in range(int(x.max())+1)] # unique list 
z = torch.stack(values, dim=0).float()
print('input data : \n \n',x)
print('_______________________________\n')
print('mask : \n ',z)

input data : 
 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [4., 4., 1., 1.],
        [4., 4., 1., 1.]])
_______________________________

mask : 
  tensor([[[1., 1., 0., 0.],
         [1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 1.],
         [0., 0., 1., 1.]],

        [[0., 0., 1., 1.],
         [0., 0., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 0., 0.],
         [1., 1., 0., 0.]]])


## Method 2 using torch.tensor_scatter_()

In [34]:
# +torch.scatter()  Out-of-place version of torch.Tensor.scatter_()
# +Syntax of torch.Tensor.scatter_():
#.       Tensor.scatter_(dim, index, src)

    

In [54]:
# defining the input data
# Case 1 : no mising labels or repeating labels 

x = torch.ones(4,4) 
x[0,:]  = torch.tensor([0, 0, 2, 2]) 
x[1,:]  = torch.tensor([0, 0, 2, 2])
x[2,:]  = torch.tensor([3, 3, 1, 1]) 
x[3,:]  = torch.tensor([3, 3, 1, 1]) 


print('input data : \n \n',x)
print('_______________________________\n')

num_classes = (x.max()+1).int() # highest cardinal number of the label+1
masks =torch.zeros(num_classes,*x.size()) # define the masks tensor
print('mask size for 2D data = ',masks.size())
print('_______________________________\n')



masks.scatter_(0, x.unsqueeze(0).data.long(), 1)  ##(dim, index, src)

input data : 
 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

mask size for 2D data =  torch.Size([4, 4, 4])
_______________________________



tensor([[[1., 1., 0., 0.],
         [1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 1.],
         [0., 0., 1., 1.]],

        [[0., 0., 1., 1.],
         [0., 0., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 0., 0.],
         [1., 1., 0., 0.]]])

In [55]:
# Case 2 : mising labels
x = torch.ones(4,4) 
x[0,:]  = torch.tensor([0, 0, 2, 2]) 
x[1,:]  = torch.tensor([0, 0, 2, 2])
x[2,:]  = torch.tensor([4, 4, 1, 1]) 
x[3,:]  = torch.tensor([4, 4, 1, 1]) 


print('input data : \n \n',x)
print('_______________________________\n')

num_classes = (x.max()+1).int() # highest cardinal number of the label+1
masks =torch.zeros(num_classes,*x.size()) # define the masks tensor
print('mask size for 2D data = ',masks.size())
print('_______________________________\n')



masks.scatter_(0, x.unsqueeze(0).data.long(), 1)  ##(dim, index, src)

input data : 
 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [4., 4., 1., 1.],
        [4., 4., 1., 1.]])
_______________________________

mask size for 2D data =  torch.Size([5, 4, 4])
_______________________________



tensor([[[1., 1., 0., 0.],
         [1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 1.],
         [0., 0., 1., 1.]],

        [[0., 0., 1., 1.],
         [0., 0., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 0., 0.],
         [1., 1., 0., 0.]]])

## Method 3 using torch.nn.functional.one_hot()

In [56]:
import torch.nn.functional as F
masks_one_hot = F.one_hot(x.data.long()) # note: the lowest cardinal number of the label starts from 0
print('input_data : \n',x)
print('_______________________________\n')
print('masks_one_hot: \n',masks_one_hot)
print('_______________________________\n')
print('masks_one_hot_size:',masks_one_hot.size())

input_data : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [4., 4., 1., 1.],
        [4., 4., 1., 1.]])
_______________________________

masks_one_hot: 
 tensor([[[1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0]],

        [[1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 0, 1, 0, 0],
         [0, 0, 1, 0, 0]],

        [[0, 0, 0, 0, 1],
         [0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0]],

        [[0, 0, 0, 0, 1],
         [0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0]]])
_______________________________

masks_one_hot_size: torch.Size([4, 4, 5])


In [57]:
print('input_data : \n',x)
print('_______________________________\n')
print(masks_one_hot.permute(2, 0, 1))

input_data : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [4., 4., 1., 1.],
        [4., 4., 1., 1.]])
_______________________________

tensor([[[1, 1, 0, 0],
         [1, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 1, 1],
         [0, 0, 1, 1]],

        [[0, 0, 1, 1],
         [0, 0, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 0, 0]]])
