## Thise code demonstartes the one_hot_encoding functionality using 3 different methods
## 1. using torch.stack()
## 2. using torch.tensor.scatter_() 
       + this would require torch.unsqueeze()
## 3. using torch.nn.functional.one_hot()


## Step 1: Define the input_data: x

In [2]:
import torch 

In [54]:
# defining the input data
x = torch.ones(4,4) 
x[0,:]  = torch.tensor([0, 0, 2, 2]) 
x[1,:]  = torch.tensor([0, 0, 2, 2])
x[2,:]  = torch.tensor([3, 3, 1, 1]) 
x[3,:]  = torch.tensor([3, 3, 1, 1]) 

In [22]:
print('input data : \n \n',x)
print('_______________________________\n')
print('input data size =', x.size())
print('_______________________________\n')
print('highest cardinal number of the  label =',int(x.max()))  #highest cardinal number of the  label 

input data : 
 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

input data size = torch.Size([4, 4])
_______________________________

highest cardinal number of the  label = 3


## Method 1  using torch.stack()

In [25]:
# range: from lowest to highest cardinal number of the label
#range from label 0 to 3, i.e., 4 classes in this case
# check if the result is compatible with the data type [YNS]

z = torch.stack([x==i for i in range(int(x.max())+1)], dim=0)

In [33]:
print('input data : \n \n',x)
print('_______________________________\n')
print('z[0] : \n ',(z[0].data.int()))
print('_______________________________\n')
print('z[1] : \n ',(z[1].data.int()))
print('_______________________________\n')
print('z[2] : \n ',(z[2].data.int()))
print('_______________________________\n')
print('z[3] : \n ',(z[3].data.int()))

input data : 
 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

z[0] : 
  tensor([[1, 1, 0, 0],
        [1, 1, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
_______________________________

z[1] : 
  tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 1]], dtype=torch.int32)
_______________________________

z[2] : 
  tensor([[0, 0, 1, 1],
        [0, 0, 1, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
_______________________________

z[3] : 
  tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 1, 0, 0],
        [1, 1, 0, 0]], dtype=torch.int32)


## Method 2 using torch.tensor_scatter_()

### Method 2 requires to understand torch.unsqueeze()
## Understanding torch.unsqueeze()


In [6]:
# torch.unsqueeze() for 1D tensor
x = torch.tensor([1, 2, 3, 4])
x_dim0 = torch.unsqueeze(x, 0)
x_dim1 = torch.unsqueeze(x, 1)
print('x size =',x.size())
print('x : \n',x)
print('_______________________________\n')

print('x_dim0 size =',x_dim0.size())
print('unsqueeze along dim 0 : \n',x_dim0)
print('_______________________________\n')
print('x_dim1 size =',x_dim1.size())
print('unsqueeze along dim 1 :\n',x_dim1)
print('_______________________________\n')





x size = torch.Size([4])
x : 
 tensor([1, 2, 3, 4])
_______________________________

x_dim0 size = torch.Size([1, 4])
unsqueeze along dim 0 : 
 tensor([[1, 2, 3, 4]])
_______________________________

x_dim1 size = torch.Size([4, 1])
unsqueeze along dim 1 :
 tensor([[1],
        [2],
        [3],
        [4]])
_______________________________



In [7]:
# torch.unsqueeze() for 2D tensor

y = torch.ones(4,4) # define a torch tensor
y[0,:]  = torch.tensor([0, 0, 2, 2]) 
y[1,:]  = torch.tensor([0, 0, 2, 2])
y[2,:]  = torch.tensor([3, 3, 1, 1]) 
y[3,:]  = torch.tensor([3, 3, 1, 1]) 
y_dim0 = torch.unsqueeze(y, 0)
y_dim1 = torch.unsqueeze(y, 1)

print('y size =',y.size())
print('y : \n',y)
print('_______________________________\n')

print('y_dim0 size =',y_dim0.size())
print('unsqueeze along dim 0 : \n',y_dim0)
print('_______________________________\n')
print('y_dim1 size =',y_dim1.size())
print('unsqueeze along dim 1 :\n',y_dim1)
print('_______________________________\n')



y size = torch.Size([4, 4])
y : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

y_dim0 size = torch.Size([1, 4, 4])
unsqueeze along dim 0 : 
 tensor([[[0., 0., 2., 2.],
         [0., 0., 2., 2.],
         [3., 3., 1., 1.],
         [3., 3., 1., 1.]]])
_______________________________

y_dim1 size = torch.Size([4, 1, 4])
unsqueeze along dim 1 :
 tensor([[[0., 0., 2., 2.]],

        [[0., 0., 2., 2.]],

        [[3., 3., 1., 1.]],

        [[3., 3., 1., 1.]]])
_______________________________



## learning torch.tensor.scatter_()

In [34]:
# +torch.scatter()  Out-of-place version of torch.Tensor.scatter_()
# +Syntax of torch.Tensor.scatter_():
#.       Tensor.scatter_(dim, index, src)

    

In [41]:
# learning torch.tensor.scatter_() for 1D  
idx = torch.tensor([0, 1, 2, 3]) 
print('labels in 1D=',idx)
print('_______________________________\n')
print('\n labels in 1D one_hot_encoded:')
torch.zeros(len(idx), idx.max()+1).scatter_(1, idx.unsqueeze(1), 1)   ##(dim, index, src)

labels in 1D= tensor([0, 1, 2, 3])
_______________________________


 labels in 1D one_hot_encoded:


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [44]:
# learning torch.tensor.scatter_() for 2D(in this case the input_data defined as x)  
print('input_data : \n',x)
print('_______________________________\n')

print('input_data size =',x.size())
print('_______________________________\n')

masks =torch.zeros(4,*x.size()) # define the masks tensor
print('mask size for 2D data = ',masks.size())
print('_______________________________\n')

#This step is required to use the labels as index for creating masks 
print('size of x.unsqueeze(0) along dim =0 :',x.unsqueeze(0).size())

input_data : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

input_data size = torch.Size([4, 4])
_______________________________

mask size for 2D data =  torch.Size([4, 4, 4])
_______________________________

size of x.unsqueeze(0) along dim =0 : torch.Size([1, 4, 4])


In [46]:
print('input_data : \n',x)
print('_______________________________\n')
# create the masks using torch.tensor.scatter_() for 2D
# along dim=0, index are the labels, src is equal to 1  

masks.scatter_(0, x.unsqueeze(0).data.long(), 1)  ##(dim, index, src)

input_data : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________



tensor([[[1., 1., 0., 0.],
         [1., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 1.],
         [0., 0., 1., 1.]],

        [[0., 0., 1., 1.],
         [0., 0., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 0., 0.],
         [1., 1., 0., 0.]]])

## Method 3 using torch.nn.functional.one_hot()

In [64]:
import torch.nn.functional as F
masks_one_hot = F.one_hot(x.data.long())
print('input_data : \n',x)
print('_______________________________\n')
print('masks_one_hot: \n',masks_one_hot)
print('_______________________________\n')
print('masks_one_hot_size:',masks_one_hot.size())

input_data : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

masks_one_hot: 
 tensor([[[1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 0]],

        [[1, 0, 0, 0],
         [1, 0, 0, 0],
         [0, 0, 1, 0],
         [0, 0, 1, 0]],

        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 0, 0]],

        [[0, 0, 0, 1],
         [0, 0, 0, 1],
         [0, 1, 0, 0],
         [0, 1, 0, 0]]])
_______________________________

masks_one_hot_size: torch.Size([4, 4, 4])


In [65]:
print('input_data : \n',x)
print('_______________________________\n')
print(masks_one_hot.permute(2, 0, 1))

input_data : 
 tensor([[0., 0., 2., 2.],
        [0., 0., 2., 2.],
        [3., 3., 1., 1.],
        [3., 3., 1., 1.]])
_______________________________

tensor([[[1, 1, 0, 0],
         [1, 1, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 1, 1],
         [0, 0, 1, 1]],

        [[0, 0, 1, 1],
         [0, 0, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [1, 1, 0, 0],
         [1, 1, 0, 0]]])
